import pandas as pd
import numpy as np
from rouge_score import rouge_scorer
import sacrebleu
from bert_score import score as bert_score
import os

GROUND_TRUTH_FILE = "Austrian Tax Law Dataset - Dataset.csv"
MODEL_FILES = {
    "Groq API Baseline": "Alikhan Janabayev sub/inference_groq.csv",
    "Fine-Tuned Local": "Alikhan Janabayev sub/fine-tuning.csv",
    "RAG Enhanced": "Alikhan Janabayev sub/rag.csv"
}

OUTPUT_RESULTS_FILE = "evaluation_results.csv"

def compute_metrics(predictions, references):
    print("Computing ROUGE...")
    scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)
    r1, r2, rl = [], [], []
    for p, r in zip(predictions, references):
        scores = scorer.score(r, p)
        r1.append(scores['rouge1'].fmeasure)
        r2.append(scores['rouge2'].fmeasure)
        rl.append(scores['rougeL'].fmeasure)
        
    print("Computing BLEU...")
    # sacrebleu expects a list of references lists
    bleu_score = sacrebleu.corpus_bleu(predictions, [references]).score

    print("Computing BERTScore (this may take a moment to download the model)...")
    # Using German language model since the dataset is Austrian German
    P, R, F1 = bert_score(predictions, references, lang="de", verbose=False)
    
    return {
        "ROUGE-1": np.mean(r1) * 100,
        "ROUGE-2": np.mean(r2) * 100,
        "ROUGE-L": np.mean(rl) * 100,
        "BLEU": bleu_score,
        "BERTScore-F1": F1.mean().item() * 100
    }

def main():
    print(f"Loading Ground Truth: {GROUND_TRUTH_FILE}")
    if not os.path.exists(GROUND_TRUTH_FILE):
        print("ERROR: Ground truth file not found!")
        return
        
    gt_df = pd.read_csv(GROUND_TRUTH_FILE)
    gt_dict = dict(zip(gt_df['id'].astype(str), gt_df['correct_answer'].astype(str)))
    
    results = []
    
    for model_name, path in MODEL_FILES.items():
        print(f"\nEvaluating: {model_name} ({path})")
        if not os.path.exists(path):
            print(f"File {path} not found. Skipping.")
            continue
            
        pred_df = pd.read_csv(path)
        # Drop rows where 'answer' is missing or just float NaN
        pred_df = pred_df.dropna(subset=['answer'])
        # Drop duplicate evaluations generated by restarted scripts
        pred_df = pred_df.drop_duplicates(subset=['id'], keep='last')
        
        predictions = []
        references = []
        
        for _, row in pred_df.iterrows():
            qid = str(row['id'])
            ans = str(row['answer'])
            if qid in gt_dict:
                predictions.append(ans)
                references.append(gt_dict[qid])
                
        if len(predictions) == 0:
            print("No matching IDs found for evaluation.")
            continue
            
        print(f"Found {len(predictions)} matched answers. Calculating...")
        metrics = compute_metrics(predictions, references)
        metrics['Model'] = model_name
        metrics['Rows Evaluated'] = len(predictions)
        
        results.append(metrics)
        print(f"Finished {model_name}: ROUGE-L {metrics['ROUGE-L']:.2f} | BLEU {metrics['BLEU']:.2f} | BERTScore {metrics['BERTScore-F1']:.2f}")

    if results:
        res_df = pd.DataFrame(results)
        # Reorder columns
        cols = ['Model', 'Rows Evaluated', 'ROUGE-1', 'ROUGE-2', 'ROUGE-L', 'BLEU', 'BERTScore-F1']
        res_df = res_df[cols]
        res_df.to_csv(OUTPUT_RESULTS_FILE, index=False)
        print(f"\n\n================ EVALUATION COMPLETE ================")
        print(f"Results saved to {OUTPUT_RESULTS_FILE}")
        print("\nSUMMARY TABLE:")
        print(res_df.to_markdown(index=False))

if __name__ == "__main__":
    main()
