# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T8tU6yeWSOc8Xgky53YveC5GDmSjhauw
"""

!pip install -q transformers datasets peft trl accelerate sentencepiece

from google.colab import files
uploaded = files.upload()

import pandas as pd

train_df = pd.read_csv("training_data.csv")
print(train_df.head())
print(train_df.columns)
print("Rows:", len(train_df))

from datasets import Dataset

train_df["text"] = train_df.apply(
    lambda row: f"Frage: {row['prompt']}\nAntwort: {row['answer']}",
    axis=1
)

train_dataset = Dataset.from_pandas(train_df[["text"]])
train_dataset

from datasets import Dataset

train_df["text"] = train_df.apply(
    lambda row: f"Frage: {row['prompt']}\nAntwort: {row['answer']}",
    axis=1
)

train_dataset = Dataset.from_pandas(train_df[["text"]])
train_dataset

from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

from peft import LoraConfig

peft_config = LoraConfig(
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

from transformers import TrainingArguments
from trl import SFTTrainer

training_args = TrainingArguments(
    output_dir="./qwen_tax_finetuned",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,
    num_train_epochs=3,
    learning_rate=2e-4,
    logging_steps=10,
    save_strategy="epoch",
    fp16=True,
    report_to="none"
)

trainer = SFTTrainer(
    model=model,
    train_dataset=train_dataset,
    peft_config=peft_config,
    args=training_args
)

trainer.train()

trainer.model.save_pretrained("qwen_tax_finetuned")
tokenizer.save_pretrained("qwen_tax_finetuned")

test_df = pd.read_csv("dataset_clean.csv")
print(test_df.head())
print("Rows:", len(test_df))

from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="qwen_tax_finetuned",
    tokenizer=tokenizer
)

def generate_answer(question):
    prompt = f"""Du bist ein Assistent für österreichisches Steuerrecht.
Beantworte die folgende Frage auf Deutsch möglichst präzise und juristisch korrekt.
Antworte in höchstens 2 kurzen Sätzen.
Keine Aufzählungen und keine Zeilenumbrüche.

Frage: {question}
Antwort:"""

    output = generator(
        prompt,
        max_new_tokens=120,
        do_sample=False,
        return_full_text=False
    )

    answer = output[0]["generated_text"].strip()
    answer = answer.replace("\n", " ").replace("\r", " ")
    answer = " ".join(answer.split())
    return answer

def generate_answer(question):
    prompt = f"""Du bist ein Assistent für österreichisches Steuerrecht.
Beantworte die folgende Frage auf Deutsch möglichst präzise und juristisch korrekt.
Antworte in höchstens 2 kurzen Sätzen.
Keine Aufzählungen und keine Zeilenumbrüche.

Frage: {question}
Antwort:"""

    output = generator(
        prompt,
        max_new_tokens=120,
        do_sample=False,
        return_full_text=False
    )

    answer = output[0]["generated_text"].strip()
    answer = answer.replace("\n", " ").replace("\r", " ")
    answer = " ".join(answer.split())
    return answer

results = []

for i, row in test_df.iterrows():
    question_id = row["id"]
    question = str(row["prompt"])

    try:
        answer = generate_answer(question)
    except Exception as e:
        answer = f"ERROR: {e}"

    results.append({
        "id": question_id,
        "answer": answer
    })

    if i % 50 == 0:
        print(f"Processed {i} / {len(test_df)}")

output_df = pd.DataFrame(results)
output_df.to_csv("nina_finetuned_qwen.csv", index=False, encoding="utf-8")
print("Done!")
print(output_df.head())
print("Rows:", len(output_df))

files.download("nina_finetuned_qwen.csv")